[package]
name = "willow-raqote"
version = { workspace = true }
edition = { workspace = true }
license = "AGPL-3.0-or-later"

[dependencies]
raqote = { workspace = true }
willow-server = { workspace = true }
