[package]
name = "willow-raqote"
version = { workspace = true }
edition = { workspace = true }
license = "AGPL-3.0-or-later"

[dependencies]
euclid = "0.22"
raqote = { workspace = true }
stackblur-iter = { version = "0.2", features = ["blend-srgb"] }
willow-server = { workspace = true }
