[workspace]
members = [
  "willow-piet",
  "willow-protocol",
  "willow-server",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
willow-piet = { path = "willow-piet " }
willow-protocol = { path = "willow-protocol" }
willow-server = { path = "willow-server" }
