[package]
name = "willow-messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
raqote = { workspace = true }
slab = { workspace = true }
softbuffer = "0.3"
willow-server = { workspace = true }
willow-raqote = { workspace = true }
winit = "0.28"
