[package]
name = "willow-server"
version = { workspace = true }
edition = { workspace = true }
license = "AGPL-3.0-or-later"

[dependencies]
slab = { workspace = true }
willow-protocol = { workspace = true }
